# Generated by Django 5.2.3 on 2025-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkinglocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('CANCELLED', 'Cancelled'), ('PAST', 'Past')], help_text='The status of this reservation.', max_length=15, verbose_name='Status'),
        ),
    ]
