# Generated by Django 5.2.3 on 2025-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('CANCELLED', 'Cancelled'), ('PAST', 'Past')], default='UPCOMING', help_text='The status of this reservation.', max_length=15, verbose_name='Status'),
        ),
    ]
